[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express", "ffmpeg-static"]
  node_bundler = "esbuild"

[[redirects]]
  force = false
  from = "/api/equipment"
  status = 200
  to = "/api/machines"

[[redirects]]
  force = false
  from = "/api/equipment/*"
  status = 200
  to = "/api/machines/:splat"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
